<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <title>Group 4 - Films</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
              rel="stylesheet"
              integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
              crossorigin="anonymous" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
        <link rel="stylesheet" href="style.css" />
    </head>
    <body class="container-fluid">

  <?php  ?>

    <?php
        if(empty($_SESSION)) {
            if($route === "inscription") {
                require "templates/inscription.phtml";
            } else {
                require "templates/connexion.phtml";
            }
        } else {
            require "templates/header.phtml";
            if($route === "show-film") {
                require "templates/show-film.phtml";
            } else if($route === "edit-film") {
                require "templates/edit-film.phtml";
            } else if($route === "administration") {
                require "templates/administration.phtml";
            } else {
                require "templates/films.phtml";
            }
        }
    ?>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
            integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js"
            integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+"
            crossorigin="anonymous"></script>
    </body>
</html>