<?php
//selection des utilisateurs
    $query = $db->prepare('SELECT * FROM Users');
    $query->execute();
    $users = $query->fetchAll(PDO::FETCH_ASSOC);
    
    $query = $db->prepare('SELECT * FROM Films');
    $query->execute();
    $films = $query->fetchAll(PDO::FETCH_ASSOC);
    
    
    
?>
<main class="container py-5">
    <h1>
        Administration
    </h1>
   
    <table class="my-5 table table-striped">
        <thead>
            <tr>
                
                <th>ID</th>
                <th>Pseudo</th>
                <th>Password</th>
                <th>Admin</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($users as $user){ ?>
            <tr>
                <td><?= $user["id"]; ?></td>
                    <td><?= $user["pseudo"]; ?></td>
                    <td><?= $user["password"]; ?></td>
                    <td><?= $user["admin"]; ?></td>
                    <td>
                        <a href="index.php?route=show-user&id=<?= $user["id"] ?>" class="btn btn-primary"><scan class="bi-eye-fill"></scan></a>
                        <a href="index.php?route=edit-user&id=<?= $user["id"] ?>" class="btn btn-success"><scan class="bi-pencil-fill"></scan></a>
                        <a href="logic/delete-user.php?id=<?= $user["id"] ?>" class="btn btn-danger"><scan class="bi-trash-fill"></scan></a>
                    </td>
            </tr>
        <?php    } ?>
    
        </tbody>    
    
    </table>
    <table class="my-5 table table-striped">
        <thead>
            <tr>
                
                <th>ID</th>
                <th>Titre</th>
                <th>Description</th>
                <th>Durée</th>
                <th>IdCateg</th>
                
            </tr>
            <tbody>
                <?php foreach ($films as $film){ ?>
                <tr>
                    <td><?= $film["id"];?></td>
                    <td><?= $film["titre"]; ?></td>
                    <td><?= $film["description"]; ?></td>
                    <td><?= $film["duree"]; ?></td>
                    <td><?= $film["idCateg"]; ?></td>
                    
                </tr>
                <?php } ?>
            </tbody>
        </thead>
    </table>
</main>






<!--if(isset($_POST["userId"]) && isset($_POST["email"]) && isset($_POST["password"]) && isset($_POST["firstName"]) && isset($_POST["lastName"]))
{
    $query = $db->prepare('UPDATE users SET email = :email, password = :password, first_name = :first_name, last_name = :last_name WHERE id = :id');
    $parameters = [
        'id' => $_POST["userId"],
        'email' => $_POST["email"],
        'password' => $_POST["password"],
        'first_name' => $_POST["firstName"],
        'last_name' => $_POST["lastName"]
    ];

    $query->execute($parameters);
}

header('Location: ../index.php');
<a href="index.php?route=show-user&id=<//?= $user["id"] ?>" class="btn btn-primary"><scan class="bi-eye-fill"></scan></a>
                        <a href="index.php?route=edit-user&id=<//?= $user["id"] ?>" class="btn btn-success"><scan class="bi-pencil-fill"></scan></a>
                        <a href="logic/delete-user.php?id=<//?= $user["id"] ?>" class="btn btn-danger"><scan class="bi-trash-fill"></scan></a>
PRENDRE LES TICONE DE LIST USER POUR FAIRE AU TOTAL 6 PAGE DANS TEMPLATE ET 2 DANS LOGIC -->