<main class="container py-5">
    <h1>Formulaire de Connexion</h1>

    <form class="mt-5" method="POST" action="logic/connexion_user.php">
    <fieldset>
        <label for="username">Nom d'utilisateur:</label>
        <input type="text" id="username" name="pseudo" required>
    </fieldset>
    <fieldset>
        <label for="password">Mot de passe:</label>
        <input type="password" id="password" name="password" required>
    </fieldset>
        <input type="submit" value="Se connecter">
    </form>
    <a href="index.php?route=inscription">Inscription</a>
</main>