
<main class="container py-5">
    <h1>Formulaire de Connexion</h1>

    <form method="POST" action="logic/connexion_user.php">
        <label for="username">Nom d'utilisateur:</label>
        <input type="text" id="username" name="pseudo" required><br>

        <label for="password">Mot de passe:</label>
        <input type="password" id="password" name="password" required><br>

        <input type="submit" value="Se connecter">
    </form>
</main>