<?php
    if(isset($_GET['id'])) {
        $id = $_GET['id'];
        $query = $db->prepare('SELECT * FROM Films WHERE id = :id');
        $parameters = [
        'id' => $id
    	];
        $query->execute($parameters);
        $user = $query->fetch(PDO::FETCH_ASSOC);
    }
?>
<main class="container py-5">
    <h1>
        Modifier un film
    </h1>
    <form class="mt-5" action="logic/edit-film.php" method="POST">
        <fieldset>
            <label for="titre" class="form-label">Titre</label>
            <input type="titre" id="titre" name="titre" class="form-control" value="<?php echo $user['titre'] ?>" />
        </fieldset>
        <fieldset>
            <label for="description" class="form-label">Description</label>
            <input type="description" id="description" name="description" class="form-control" value="<?php echo $user['description'] ?>" />
        </fieldset>
        <fieldset>
            <label for="firstName" class="form-label">Durée</label>
            <input type="text" id="firstName" name="firstName" class="form-control" value="<?php echo $user['duree'] ?>" />
        </fieldset>

        <button type="submit" class="mt-3 btn btn-primary">Sauvegarder</button>
    </form>
</main>