<main class="container py-5">
    <h1>
        Créer un utilisateur
    </h1>
    <form class="mt-5" action="logic/create-user.php" method="POST">
        <fieldset>
            <label for="pseudo" class="form-label">Pseudo</label>
            <input type="pseudo" id="pseudo" name="pseudo" class="form-control" />
        </fieldset>
        <fieldset>
            <label for="password" class="form-label">Mot de passe</label>
            <input type="password" id="password" name="password" class="form-control" />
        </fieldset>
        <fieldset>
            <label for="admin" class="form-label">Admin</label>
            <input type="checkbox" id="admin" name="admin" />
        </fieldset>
        <button type="submit" class="mt-3 btn btn-primary">Inscription</button>
    </form>
    <a href="index.php?route=connexion">Connexion</a>
</main>