<?php
    if(isset($_GET['id'])) {
        $idFilm = $_GET['id'];
        $query = $db->prepare('SELECT Films.titre, Films.description, Categories.type FROM Films JOIN Categories ON Films.idCateg = Categories.id WHERE Films.id = :id');
        $parameters = [
        'id' => $idFilm
    	];
        $query->execute($parameters);
        $film = $query->fetch(PDO::FETCH_ASSOC);
    }
?>
<main class="container py-5">
    <h1>
        <?php 
            echo $film['titre'];
        ?>
    </h1>
    <h2>
        <?php 
            echo $film['description'];
        ?>
    </h2>
    <h3>
        <?php 
            echo $film['type'];
        ?>
    </h3>
</main>